from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path

from app.config.settings import get_settings
from app.ingestion.checkpoint_repository import CheckpointRepository
from app.ingestion.delta_detector import DeltaDetector
from app.ingestion.entity_registry import get_entity_config, list_entity_configs
from app.ingestion.models import (
    DeltaAction,
    IngestionBatchStatus,
    IngestionRecordResult,
    IngestionRunRequest,
    IngestionRunResponse,
    IngestionStatus,
)
from app.ingestion.tigergraph_upsert import TigerGraphUpsertClient
from app.ingestion.validation_engine import ValidationEngine
from app.shared.ids import normalize_account_key, timestamp_id

# Persist the batch checkpoint every N rows (plus at every batch boundary and on
# completion/failure) — one SQLite fsync per N rows instead of per row.
_CHECKPOINT_EVERY = 200


class IngestionService:
    def __init__(self) -> None:
        self.settings = get_settings()
        self.checkpoints = CheckpointRepository()
        self.validator = ValidationEngine()
        self.delta = DeltaDetector(self.checkpoints)
        self.upsert = TigerGraphUpsertClient()
        # CSV base directory (manifest file paths are relative to it:
        # vertices/*.csv and edges/*.csv). Generated by scripts/generate_mock_data.py.
        self.data_dir = self.settings.resolved_data_dir

    def list_entities(self) -> list[dict]:
        return [config.model_dump() for config in list_entity_configs()]

    # ------------------------------------------------------------- delete

    def delete_plan(self) -> list[dict]:
        """The ordered delete sequence, shown in the confirm dialog: edges first
        (reverse manifest order), then vertices (reverse manifest order) — facts
        before dimensions."""
        configs = list_entity_configs()
        edges = [c for c in configs if c.kind == "edge"]
        vertices = [c for c in configs if c.kind == "vertex"]
        plan = list(reversed(edges)) + list(reversed(vertices))
        return [{"entity_name": c.entity_name, "kind": c.kind, "target": c.tigergraph_vertex}
                for c in plan]

    def delete_entity(self, entity_name: str) -> dict:
        """Delete one entity's rows from the graph and clear its checkpoints.

        NEVER raises: every failure is caught, recorded with its reason, and
        returned as outcome='failed' so the endpoint answers 200 with a report
        instead of a 500 (whose missing CORS headers would mask the real error).

        Edge types: bulk-deletable on the local tier; on a real TigerGraph edges
        can only disappear with their endpoint vertices, and that limitation is
        REPORTED, never silently swallowed."""
        config = get_entity_config(entity_name)
        graph = self.upsert.graph
        try:
            result = graph.delete_all(config.tigergraph_vertex, kind=config.kind)
            outcome = "deleted"
        except Exception as exc:  # noqa: BLE001 — surfaced, not hidden
            if config.kind == "edge":
                result = {
                    "error": False, "deleted": 0, "target": config.tigergraph_vertex,
                    "note": f"edge type not bulk-deletable on this tier ({exc}); "
                            "its edges are removed when their endpoint vertices are deleted",
                }
                outcome = "deleted"
            else:
                result = {
                    "error": True, "deleted": 0, "target": config.tigergraph_vertex,
                    "reason": f"{type(exc).__name__}: {exc}",
                }
                outcome = "failed"
        if outcome == "deleted":
            # only a confirmed delete clears checkpoints — a failed delete keeps
            # them so screen state and graph state stay consistent
            self.checkpoints.clear_entity(config.entity_name)
        return {"entity_name": config.entity_name, "kind": config.kind, "outcome": outcome, **result}

    def delete_all_entities(self) -> dict:
        """Ordered full delete: every entity per delete_plan(). One failing entity
        never aborts the rest — each outcome is collected and the full per-entity
        report returned. Checkpoints are cleared per confirmed entity so the next
        load re-writes everything."""
        results = [self.delete_entity(step["entity_name"]) for step in self.delete_plan()]
        failed = [r for r in results if r.get("outcome") == "failed"]
        return {
            "deleted_entities": len(results) - len(failed),
            "failed_entities": len(failed),
            "failed": [{"entity_name": r["entity_name"], "reason": r.get("reason")} for r in failed],
            "total_rows_deleted": sum(int(r.get("deleted") or 0) for r in results),
            "order": [r["entity_name"] for r in results],
            "results": results,
        }

    def clear_checkpoints(self, entity_name: str | None = None) -> dict:
        """Clear checkpoint state (batches + row hashes) for one entity or all —
        the graph is NOT touched. Exposed for the clean-slate procedure."""
        if entity_name:
            config = get_entity_config(entity_name)  # validates the name
            self.checkpoints.clear_entity(config.entity_name)
            cleared = [config.entity_name]
        else:
            cleared = []
            for config in list_entity_configs():
                self.checkpoints.clear_entity(config.entity_name)
                cleared.append(config.entity_name)
        return {"cleared_entities": len(cleared), "entities": cleared,
                "note": "graph data untouched; next load re-writes everything"}

    def list_batches(self) -> list[dict]:
        return self.checkpoints.list_batches()

    def _count_records(self, file_path: Path) -> int:
        # csv-aware, BOM-tolerant count — a quoted value containing a newline is ONE
        # record, and a BOM must not corrupt the first header.
        with file_path.open(newline="", encoding="utf-8-sig") as f:
            return max(0, sum(1 for _ in csv.reader(f)) - 1)

    def run_entity_ingestion(self, request: IngestionRunRequest) -> IngestionRunResponse:
        config = get_entity_config(request.entity_name)
        file_name = request.file_name or config.csv_file_name
        file_path = self.data_dir / file_name
        if not file_path.exists():
            raise FileNotFoundError(f"CSV file not found: {file_path}")

        is_edge = config.kind == "edge"
        from_col = config.from_column or "from_id"
        to_col = config.to_column or "to_id"

        total_records = self._count_records(file_path)
        previous = self.checkpoints.latest_batch(config.entity_name, file_name) if request.resume else None

        should_resume = (
            request.resume
            and previous is not None
            and previous.status in {IngestionStatus.FAILED, IngestionStatus.PAUSED, IngestionStatus.RUNNING}
        )
        start_row = previous.last_processed_row + 1 if should_resume else 1

        status = IngestionBatchStatus(
            batch_id=previous.batch_id if should_resume else timestamp_id("batch"),
            entity_name=config.entity_name,
            file_name=file_name,
            status=IngestionStatus.RUNNING,
            total_records=total_records,
            processed_records=previous.processed_records if should_resume else 0,
            created_records=previous.created_records if should_resume else 0,
            updated_records=previous.updated_records if should_resume else 0,
            skipped_records=previous.skipped_records if should_resume else 0,
            failed_records=previous.failed_records if should_resume else 0,
            last_processed_row=previous.last_processed_row if should_resume else 0,
            progress_percent=previous.progress_percent if should_resume else 0,
            message="Running",
        )
        self.checkpoints.save_batch(status)

        results: list[IngestionRecordResult] = []
        batch_size = request.batch_size or config.batch_size

        # One read for all known hashes; one bulk write per flush — instead of a
        # SQLite connection + fsync per row (untenable at high-volume edge files).
        known_hashes = self.checkpoints.get_hashes(config.entity_name)
        pending_rows: list[dict] = []
        pending_hashes: list[tuple[str, str]] = []
        pending_first_row: list[int] = []  # row number of the first unflushed row
        pending_actions: list[DeltaAction] = []  # per pending row: CREATE or UPDATE
        pending_result_idx: list[int] = []  # index into results[] for each pending row

        def _record_pk(record: dict) -> str:
            if is_edge:
                return f"{record.get(from_col, '')}->{record.get(to_col, '')}"
            return record.get(config.primary_key, "")

        def _flush_writes() -> None:
            """Push the accumulated rows to the graph in ONE adapter call, then —
            ONLY after the graph confirmed the write — persist their hashes and add
            them to the created/updated tallies (a checkpoint must never record a
            write the graph did not confirm)."""
            if not pending_rows:
                return
            if not request.dry_run:
                if is_edge:
                    self.upsert.upsert_edge_rows(config.tigergraph_vertex, list(pending_rows))
                else:
                    self.upsert.upsert_vertex_rows(
                        config.tigergraph_vertex, list(pending_rows), id_column=config.primary_key
                    )
                self.checkpoints.upsert_hashes(config.entity_name, pending_hashes)
            status.created_records += sum(1 for a in pending_actions if a == DeltaAction.CREATE)
            status.updated_records += sum(1 for a in pending_actions if a == DeltaAction.UPDATE)
            pending_rows.clear()
            pending_hashes.clear()
            pending_first_row.clear()
            pending_actions.clear()
            pending_result_idx.clear()

        def _mark_pending_failed(reason: str) -> None:
            """A flush failed: the pending rows did NOT land. Correct their optimistic
            per-row results and rewind the checkpoint so a resume retries them."""
            for idx in pending_result_idx:
                results[idx].action = DeltaAction.FAILED
                results[idx].success = False
                results[idx].message = f"Not persisted — graph write failed: {reason}"
            if pending_first_row:
                status.last_processed_row = pending_first_row[0] - 1

        def _save_status() -> None:
            status.updated_at = datetime.utcnow()
            self.checkpoints.save_batch(status)

        with file_path.open(newline="", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            header_errors = self.validator.validate_header(
                config, reader.fieldnames or [], file_name=file_name
            )
            if header_errors:
                status.status = IngestionStatus.FAILED
                status.message = "; ".join(header_errors)
                _save_status()
                self.checkpoints.save_error(
                    error_id=timestamp_id("err"),
                    batch_id=status.batch_id,
                    entity_name=config.entity_name,
                    row_number=0,
                    primary_key=None,
                    error_message=status.message,
                    raw_record={"header": reader.fieldnames or []},
                )
                return IngestionRunResponse(batch_status=status, records=[])

            for row_number, record in enumerate(reader, start=1):
                if row_number < start_row:
                    continue

                # Account keys go through THE shared normalisation before anything
                # else sees them — the primary key, delta hash, validation and the
                # graph write all operate on the normalised value, so a real CSV
                # with padded/zero-prefixed keys joins cleanly against the graph.
                for col in config.normalize_columns:
                    if record.get(col) is not None:
                        record[col] = normalize_account_key(record[col])

                primary_key = _record_pk(record)
                try:
                    validation_errors = self.validator.validate_record(config, record)
                    if validation_errors:
                        raise ValueError("; ".join(validation_errors))

                    new_hash = self.delta.row_hash(record)
                    old_hash = known_hashes.get(primary_key)
                    if old_hash == new_hash:
                        action = DeltaAction.SKIP
                        status.skipped_records += 1
                        message = "Unchanged"
                    else:
                        action = DeltaAction.CREATE if old_hash is None else DeltaAction.UPDATE
                        if not pending_rows:
                            pending_first_row.append(row_number)
                        pending_rows.append(record)
                        pending_hashes.append((primary_key, new_hash))
                        pending_actions.append(action)
                        pending_result_idx.append(len(results))
                        known_hashes[primary_key] = new_hash
                        # created/updated tallies advance in _flush_writes, only after
                        # the graph confirms the batch.
                        message = action.value

                    status.processed_records += 1
                    status.last_processed_row = row_number
                    status.progress_percent = (
                        round((status.last_processed_row / total_records) * 100, 2) if total_records else 100
                    )
                    if status.processed_records % _CHECKPOINT_EVERY == 0:
                        _save_status()

                    results.append(
                        IngestionRecordResult(
                            row_number=row_number,
                            entity_name=config.entity_name,
                            primary_key=primary_key,
                            action=action,
                            success=True,
                            message=message,
                        )
                    )

                except Exception as exc:
                    status.failed_records += 1
                    status.processed_records += 1
                    status.last_processed_row = row_number
                    status.progress_percent = (
                        round((status.last_processed_row / total_records) * 100, 2) if total_records else 100
                    )
                    status.status = IngestionStatus.FAILED
                    status.message = f"Failed at row {row_number}: {exc}"
                    _save_status()
                    self.checkpoints.save_error(
                        error_id=timestamp_id("err"),
                        batch_id=status.batch_id,
                        entity_name=config.entity_name,
                        row_number=row_number,
                        primary_key=primary_key,
                        error_message=str(exc),
                        raw_record=record,
                    )
                    results.append(
                        IngestionRecordResult(
                            row_number=row_number,
                            entity_name=config.entity_name,
                            primary_key=primary_key,
                            action=DeltaAction.FAILED,
                            success=False,
                            message=str(exc),
                        )
                    )
                    return IngestionRunResponse(batch_status=status, records=results[-batch_size:])

                if len(results) >= batch_size:
                    # Return after one batch so UI can show progress and call repeatedly.
                    try:
                        _flush_writes()
                    except Exception as exc:  # graph write failed for this batch
                        status.status = IngestionStatus.FAILED
                        status.message = f"Graph write failed at row {row_number}: {exc}"
                        _mark_pending_failed(str(exc))
                        _save_status()
                        self.checkpoints.save_error(
                            error_id=timestamp_id("err"),
                            batch_id=status.batch_id,
                            entity_name=config.entity_name,
                            row_number=pending_first_row[0] if pending_first_row else row_number,
                            primary_key=None,
                            error_message=f"Graph write failed (batch not persisted): {exc}",
                            raw_record={},
                        )
                        return IngestionRunResponse(batch_status=status, records=results[-batch_size:])
                    status.message = "Batch completed; call again to continue if needed."
                    _save_status()
                    return IngestionRunResponse(batch_status=status, records=results[-batch_size:])

        try:
            _flush_writes()
        except Exception as exc:
            status.status = IngestionStatus.FAILED
            status.message = f"Graph write failed on final flush: {exc}"
            _mark_pending_failed(str(exc))
            _save_status()
            self.checkpoints.save_error(
                error_id=timestamp_id("err"),
                batch_id=status.batch_id,
                entity_name=config.entity_name,
                row_number=pending_first_row[0] if pending_first_row else status.last_processed_row,
                primary_key=None,
                error_message=f"Graph write failed on final flush (batch not persisted): {exc}",
                raw_record={},
            )
            return IngestionRunResponse(batch_status=status, records=results[-batch_size:])
        status.status = IngestionStatus.COMPLETED
        status.progress_percent = 100.0
        status.message = "Completed"
        _save_status()
        return IngestionRunResponse(batch_status=status, records=results[-batch_size:])
