"""Round F task 4.2 — write docs/data/extraction/*.sql with the cohort SIDs baked in.

    python3 scripts/generate_extraction_sql.py [--cohort data/real/cohort.txt]
                                               [--out docs/data/extraction]

Reads cohort.txt (written by scripts/select_cohort.py) and emits one .sql file per
raw extract in RAW_CONTRACT (scripts/build_real_data.py). The SQL is run BY A HUMAN
against the client's PostgreSQL (schema pcr, db fpicdb) — the app never reaches it.
Save each result as CSV (header row, comma-separated, UTF-8) under data/real/_raw/
with the exact raw_*.csv filename shown in each header comment.

Corrections baked in (ROUND_D_EXTRACTION.md §4, client-confirmed):
  - raw_acct_eci_map: source column IS new_exst_adv_clnt_in_cyr (no rename in SQL —
    build_real_data.py maps it to the graph's new_exst_adv_clnt_in);
    latest bus_dt per (wm_src_sys_cd, wm_acct_src_nb) only.
  - raw_monthly_balance: columns are acct_id, acct_bal; all three month tables
    unioned with an explicit month_id.
  - raw_advisor: includes transfer counterparties outside the cohort with
    in_cohort=false (or every transfer edge pointing at them drops at load).
  - raw_adv_flows: April and May only; other_attributes JSONB flattened into the
    six named columns.
  - month meta: expect 30/31/30 calendar days (the table accrues daily).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

HEADER = """-- GENERATED by scripts/generate_extraction_sql.py from {cohort_path}
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/{csv_name}
"""


def sid_list(sids: list[str], indent: int) -> str:
    pad = " " * indent
    lines = [",".join(f"'{s}'" for s in sids[i:i + 5]) for i in range(0, len(sids), 5)]
    return f",\n{pad}".join(lines)


def templates(sids: list[str]) -> dict[str, str]:
    in_cohort = sid_list(sids, 25)
    return {
        # ---- step 1: cohort selection (no SIDs — run BEFORE select_cohort.py) ----
        "raw_advisor_flags.sql": """
-- Step 1, run FIRST (feeds scripts/select_cohort.py — no cohort filter yet).
-- Scores every advisor with in-scope trades on the nine scenario flags.
-- grid_reduction is SCARCE (~99 accounts firmwide) — the selector takes it first.
WITH scoped AS (
  SELECT d.advisor_sid, d.account_no, d.post_split_credited_amt, d.reason_cd,
         d.standard_rate_bps, d.client_rate_bps, d.grid_reduction
  FROM   pcr.fpic_daily_trade_details_tb_prod d
  WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
)
SELECT s.advisor_sid,
       max(r.prm_rr_no)                          AS rep_code,
       max(e.em_name_txt)                        AS advisor_name,
       sum(CASE WHEN COALESCE(NULLIF(trim(s.reason_cd),''),'__NONE__') = '__NONE__'
                THEN s.post_split_credited_amt ELSE 0 END) AS total_credited_amt,
       bool_or(s.standard_rate_bps > 0 AND
               (s.standard_rate_bps - s.client_rate_bps) / s.standard_rate_bps * 100 > 10)
                                                 AS has_fee_reduction_gt10,
       bool_or(COALESCE(s.grid_reduction,0) <> 0) AS has_recorded_grid_reduction,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_rr_changes_from_nacs_logs c
                       WHERE c.to_mem_sid = s.advisor_sid
                         AND c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'))
                                                 AS has_transfer_in,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_rr_changes_from_nacs_logs c
                       WHERE c.from_mem_sid = s.advisor_sid
                         AND c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'))
                                                 AS has_transfer_out,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_acct_tb_pm a
                       WHERE ltrim(trim(a.account_number),'0') = ltrim(trim(s.account_no),'0')
                         AND to_timestamp(NULLIF(trim(a.account_open_dt),''),
                                          'MM/DD/YYYY HH12:MI:SS AM')
                             >= DATE '2026-04-01'
                         AND to_timestamp(NULLIF(trim(a.account_open_dt),''),
                                          'MM/DD/YYYY HH12:MI:SS AM')
                             <  DATE '2026-07-01'))
                                                 AS has_new_account,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_monthly_acct_balance_tb_april b4
                       JOIN pcr.fpic_monthly_acct_balance_tb_may b5
                         ON ltrim(trim(b5.acct_id),'0') = ltrim(trim(b4.acct_id),'0')
                       WHERE ltrim(trim(b4.acct_id),'0') = ltrim(trim(s.account_no),'0')
                         AND b4.acct_bal > 0 AND b5.acct_bal = 0))
                                                 AS has_zeroed_account,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_team_agreement_tb t
                       WHERE (t.prm_standard_id = s.advisor_sid OR t.sec_standard_id = s.advisor_sid)
                         AND t.team_agreement_status_cd = 'ACTIVE'))
                                                 AS has_team_agreement,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_daily_adv_flows_tb_pm f
                       WHERE f.rep_wrkr_sid = s.advisor_sid))
                                                 AS has_flows,
       bool_or(NULLIF(trim(s.reason_cd),'') IS NOT NULL)
                                                 AS has_non_credited
FROM   scoped s
JOIN   pcr.fpic_prm_rr_tb r ON r.standard_id = s.advisor_sid
LEFT   JOIN pcr.fpic_employee_tb e ON e.em_standard_id = s.advisor_sid
GROUP  BY s.advisor_sid;
""",
        "raw_advisor.sql": f"""
-- Cohort advisors (in_cohort=true) PLUS every transfer counterparty
-- (in_cohort=false) — miss them and every transfer edge pointing at them
-- drops silently at load. Blank names stay blank; never invent one.
WITH cohort(advisor_sid) AS (
  SELECT unnest(ARRAY[{sid_list(sids, 25)}])
),
counterparties AS (
  SELECT DISTINCT c.from_mem_sid AS advisor_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
    AND  c.to_mem_sid IN (SELECT advisor_sid FROM cohort)
  UNION
  SELECT DISTINCT c.to_mem_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
    AND  c.from_mem_sid IN (SELECT advisor_sid FROM cohort)
)
SELECT r.standard_id                              AS advisor_sid,
       r.prm_rr_no                                AS rep_code,
       COALESCE(e.em_name_txt,'')                 AS advisor_name,
       r.cwm_branch_cd                            AS branch_cd,
       COALESCE(e.em_standard_id,'')              AS employee_id,
       (r.standard_id IN (SELECT advisor_sid FROM cohort)) AS in_cohort
FROM   pcr.fpic_prm_rr_tb r
LEFT   JOIN pcr.fpic_employee_tb e ON e.em_standard_id = r.standard_id
WHERE  r.standard_id IN (SELECT advisor_sid FROM cohort)
   OR  r.standard_id IN (SELECT advisor_sid FROM counterparties);
""",
        "raw_account.sql": f"""
-- Accounts with in-scope cohort trades. Current snapshot — do NOT extract
-- financial_advisor_cd (no date column; historical attribution mis-assigns).
-- No PII columns, ever.
SELECT DISTINCT
       a.account_number                           AS account_no,
       a.account_class_cd, a.account_class_nm, a.account_lob_cd,
       a.account_purpose_cd, a.managed_platform_cd, a.service_channel_cd,
       COALESCE(to_char(to_timestamp(NULLIF(trim(a.account_open_dt),''),
                                     'MM/DD/YYYY HH12:MI:SS AM'),
                        'YYYY-MM-DD HH24:MI:SS'),'') AS account_open_dt,
       COALESCE(a.party_primary_eci,'')           AS primary_eci_id
FROM   pcr.fpic_acct_tb_pm a
WHERE  ltrim(trim(a.account_number),'0') IN (
         SELECT DISTINCT ltrim(trim(d.account_no),'0')
         FROM   pcr.fpic_daily_trade_details_tb_prod d
         WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
           AND  d.advisor_sid IN ({in_cohort})
       );
""",
        "raw_product_hierarchy.sql": """
-- Product taxonomy. grid_type pulled as a column; build filters PRODUCT_TYPE.
SELECT DISTINCT
       h.product_code                             AS product_cd,
       COALESCE(h.sub_product_code,'')            AS product_sub_cd,
       h.level_two_product                        AS product_name,
       h.level_one_product                        AS sor,
       ''                                         AS file_key,
       h.grid_type
FROM   pcr.product_hierarchy h;
""",
        "raw_revenue_transaction.sql": f"""
-- THE 48M-ROW TABLE: filter to cohort + date range BEFORE anything else or it
-- times out. Credited revenue = post_split_credited_amt (pre_split x split_pct
-- double-counts across advisors). NEVER join fpic_team_agreement_tb here.
-- Month derives from trade_dt in the build script — never proc_dt.
SELECT d.trade_ref_no, d.split_seq_no, d.advisor_sid,
       d.account_no, d.product_cd, d.product_sub_cd,
       d.trade_dt, d.proc_dt,
       d.post_split_credited_amt, d.pre_split_credited_amt, d.split_pct,
       COALESCE(NULLIF(trim(d.reason_cd),''),'') AS reason_cd,
       d.standard_rate_bps, d.client_rate_bps,
       d.discount_amt, d.eff_disc_pct, d.grid_reduction,
       COALESCE(d.rpg,'')                        AS rpg,
       COALESCE(d.concession_type,'')            AS concession_type,
       COALESCE(d.file_key,'')                   AS file_key,
       COALESCE(d.trade_description,'')          AS trade_description
FROM   pcr.fpic_daily_trade_details_tb_prod d
WHERE  d.trade_dt >= DATE '2026-04-01'
  AND  d.trade_dt <  DATE '2026-07-01'
  AND  d.advisor_sid IN ({in_cohort});
""",
        "raw_rr_changes.sql": f"""
-- Account transfers touching a cohort advisor, in scope.
SELECT c.occd_cd, c.account_no, c.transfer_ts, c.seq_no,
       c.from_rr, c.from_mem_sid, c.to_rr, c.to_mem_sid
FROM   pcr.fpic_rr_changes_from_nacs_logs c
WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
  AND  (c.from_mem_sid IN ({in_cohort})
   OR   c.to_mem_sid   IN ({sid_list(sids, 26)}));
""",
        "raw_monthly_balance.sql": f"""
-- Month-end balances: columns confirmed acct_id / acct_bal. Three month tables
-- unioned with an explicit month_id. Restricted to cohort-traded accounts.
WITH cohort_accts AS (
  SELECT DISTINCT ltrim(trim(d.account_no),'0') AS acct_key
  FROM   pcr.fpic_daily_trade_details_tb_prod d
  WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
    AND  d.advisor_sid IN ({in_cohort})
)
SELECT '202604' AS month_id, b.acct_id, b.acct_bal
FROM   pcr.fpic_monthly_acct_balance_tb_april b
WHERE  ltrim(trim(b.acct_id),'0') IN (SELECT acct_key FROM cohort_accts)
UNION ALL
SELECT '202605', b.acct_id, b.acct_bal
FROM   pcr.fpic_monthly_acct_balance_tb_may b
WHERE  ltrim(trim(b.acct_id),'0') IN (SELECT acct_key FROM cohort_accts)
UNION ALL
SELECT '202606', b.acct_id, b.acct_bal
FROM   pcr.fpic_monthly_acct_balance_tb_june b
WHERE  ltrim(trim(b.acct_id),'0') IN (SELECT acct_key FROM cohort_accts);
""",
        "raw_month_meta.sql": f"""
-- Month meta: trading_days = distinct trade dates. The table accrues DAILY
-- (weekends have rows), so expect calendar-day counts 30 / 31 / 30 and
-- is_partial=false for all three months (client Phase 0 confirmed June complete).
SELECT to_char(d.trade_dt,'YYYYMM')              AS month_id,
       to_char(date_trunc('month', min(d.trade_dt)),'YYYY-MM-DD HH24:MI:SS') AS start_dt,
       to_char(max(d.trade_dt),'YYYY-MM-DD HH24:MI:SS')                      AS end_dt,
       count(DISTINCT d.trade_dt)                AS trading_days
FROM   pcr.fpic_daily_trade_details_tb_prod d
WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
  AND  d.advisor_sid IN ({in_cohort})
GROUP  BY 1 ORDER BY 1;
""",
        "raw_acct_eci_rel.sql": f"""
-- Account <-> household party, ALL relationship codes (incl. 802 Beneficiary).
SELECT r.account_number, r.party_eci_id, r.enterprise_relationship_code,
       COALESCE(r.party_role_name,'')            AS party_role_name,
       COALESCE(r.client_employee_ind,'')        AS client_employee_ind
FROM   pcr.fpic_acct_eci_rel_tb_pm r
WHERE  ltrim(trim(r.account_number),'0') IN (
         SELECT DISTINCT ltrim(trim(d.account_no),'0')
         FROM   pcr.fpic_daily_trade_details_tb_prod d
         WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
           AND  d.advisor_sid IN ({in_cohort})
       );
""",
        "raw_acct_eci_map.sql": f"""
-- Cross-system account <-> ECI map. DAILY SNAPSHOT: latest bus_dt per
-- (wm_src_sys_cd, wm_acct_src_nb) only. Source column IS
-- new_exst_adv_clnt_in_cyr — the graph column has no _cyr; build_real_data.py
-- does the rename. bus_dt is varchar; cast it.
WITH cohort_accts AS (
  SELECT DISTINCT ltrim(trim(d.account_no),'0') AS acct_key
  FROM   pcr.fpic_daily_trade_details_tb_prod d
  WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
    AND  d.advisor_sid IN ({in_cohort})
),
ranked AS (
  SELECT m.bus_dt, m.wm_src_sys_cd, m.wm_acct_src_nb, m.eci_nb,
         m.new_exst_adv_clnt_in_cyr,
         row_number() OVER (PARTITION BY m.wm_src_sys_cd, m.wm_acct_src_nb
                            ORDER BY m.bus_dt::date DESC) AS rn
  FROM   pcr.fpic_acct_eci_map_tb m
  WHERE  ltrim(trim(m.wm_acct_src_nb),'0') IN (SELECT acct_key FROM cohort_accts)
)
SELECT bus_dt, wm_src_sys_cd, wm_acct_src_nb, eci_nb, new_exst_adv_clnt_in_cyr
FROM   ranked WHERE rn = 1;
""",
        "raw_team_agreement.sql": f"""
-- Team splits — REFERENCE DATA ONLY. Never joined to trades
-- (post_split_credited_amt already carries the split; the join fans out one
-- row per secondary member). Shares stay as fractions 0.0-1.0.
SELECT t.agreement_id, t.team_rep_cd, t.team_agreement_typ,
       t.team_agreement_status_cd,
       t.prm_standard_id, t.prm_share_pct, t.sec_standard_id, t.sec_share_pct,
       t.start_ts, t.end_ts
FROM   pcr.fpic_team_agreement_tb t
WHERE  (t.prm_standard_id IN ({in_cohort})
   OR   t.sec_standard_id IN ({sid_list(sids, 26)}))
  AND  t.start_ts < DATE '2026-07-01'
  AND  (t.end_ts IS NULL OR t.end_ts >= DATE '2026-04-01');
""",
        "raw_adv_flows.sql": f"""
-- Advisor flows: APRIL AND MAY ONLY (no June rows exist). other_attributes
-- JSONB flattened into the six named columns — 0 / empty where absent.
SELECT r.standard_id                             AS advisor_sid,
       to_char(f.bus_dt::date,'YYYYMM')          AS month_id,
       f.cwm_flow_comp_prod_cd                   AS flow_product_cd,
       COALESCE(f.cwm_flow_comp_prod_desc_tx,'') AS flow_product_desc,
       COALESCE(f.cwm_comp_group_type,'')        AS comp_group_type,
       sum(COALESCE(f.total_inflows_am,0))       AS total_inflows,
       sum(COALESCE(f.total_outflows_am,0))      AS total_outflows,
       sum(COALESCE(f.total_net_financial_flows,0))          AS total_net_flows,
       sum(COALESCE(f.total_cwm_comp_credited_flows_am,0))   AS credited_flows,
       max(COALESCE(f.other_attributes->>'departed_advisor_sid',''))       AS departed_advisor_sid,
       sum(COALESCE((f.other_attributes->>'departed_advisor_excl_am')::numeric,0))   AS departed_advisor_excl_am,
       sum(COALESCE((f.other_attributes->>'lob_trfr_excl_am')::numeric,0))           AS lob_trfr_excl_am,
       sum(COALESCE((f.other_attributes->>'oi_pa_referral_cap_adj_am')::numeric,0))  AS oi_pa_referral_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'large_flow_cap_adj_am')::numeric,0))      AS large_flow_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'forced_closure_excl_am')::numeric,0))     AS forced_closure_excl_am
FROM   pcr.fpic_daily_adv_flows_tb_pm f
JOIN   pcr.fpic_prm_rr_tb r
       ON r.standard_id = f.rep_wrkr_sid OR r.prm_rr_no = f.pri_rep_cd
WHERE  f.bus_dt::date >= DATE '2026-04-01' AND f.bus_dt::date < DATE '2026-06-01'
  AND  r.standard_id IN ({in_cohort})
GROUP  BY 1, 2, 3, 4, 5;
""",
        "raw_crm_opportunity.sql": f"""
-- Round F2: the CRM opportunity extract, COHORT-FILTERED (the firm-wide file
-- is 308,534 rows — far more than a 20-advisor demo needs). Table located via
-- docs/data/extraction/discovery_crm_amount.sql STEP 0; replace <crm_table>
-- with the schema-qualified name it returned.
-- Invalid advisor references (e.g. 'I817209_CWM_INVALID') are INCLUDED on
-- purpose — build_real_data.py strips the suffix, keeps the raw value, sets
-- advisor_valid=false and REPORTS the count. Never filter them out here.
-- The eci__c half of the filter keeps opportunities on cohort households
-- whose owner sid is invalid or missing.
SELECT o.id                                    AS opportunity_id,
       COALESCE(o.eci__c,'')                   AS eci_id,
       COALESCE(o.ownersid__c,'')              AS ownersid,
       COALESCE(o.account_record_type_name__c,'') AS account_record_type,
       COALESCE(o.product_service_type__c,'')  AS product_service_type,
       COALESCE(o.stagename,'')                AS stage_name,
       COALESCE(o.amount,0)                    AS amount,
       COALESCE(o.actual_assets__c,0)          AS actual_assets,
       o.anticipated_investment_date__c        AS anticipated_investment_dt,
       o.createddate                           AS created_dt,
       o.lastmodifieddate                      AS last_modified_dt,
       o.date_of_last_contact__c               AS date_of_last_contact,
       COALESCE(o.days_to_close,0)             AS days_to_close,
       COALESCE(o.additional_comments__c,'')   AS comments
FROM   <crm_table> o
WHERE  regexp_replace(COALESCE(o.ownersid__c,''), '_.*$', '') IN ({in_cohort})
   OR  o.eci__c IN (
         SELECT DISTINCT r.party_eci_id
         FROM   pcr.fpic_acct_eci_rel_tb_pm r
         JOIN   pcr.fpic_revenue_transaction_tb_pm t
                ON ltrim(trim(t.account_no),'0') = ltrim(trim(r.account_number),'0')
         WHERE  t.advisor_sid IN ({in_cohort})
       );
""",
    }
    # NOTE (Round F2): the four NNM files (ECNNM_/NBNNM_/YINNM_/FSNNM_*.txt)
    # are DELIVERED FILES, not SQL extracts — there is no SQL template for
    # them. Drop them into data/real/_raw/ as received; scripts/parse_nnm.py
    # reads the pipe-delimited format directly (H header line, D-prefixed
    # dates, negatives preserved).


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cohort", default="data/real/cohort.txt")
    ap.add_argument("--out", default="docs/data/extraction")
    args = ap.parse_args()

    cohort_path = Path(args.cohort)
    if not cohort_path.exists():
        print(f"ERROR: {cohort_path} not found — run scripts/select_cohort.py first",
              file=sys.stderr)
        return 1
    sids = [ln.strip() for ln in cohort_path.read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.startswith("#")]
    if not sids:
        print(f"ERROR: {cohort_path} contains no advisor SIDs", file=sys.stderr)
        return 1
    print(f"cohort: {len(sids)} advisors from {cohort_path}")

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for fname, body in templates(sids).items():
        csv_name = fname.replace(".sql", ".csv")
        text = HEADER.format(cohort_path=cohort_path, csv_name=csv_name) + body.lstrip("\n")
        (out / fname).write_text(text, encoding="utf-8")
        print(f"wrote {out / fname}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
