"""Round F task 4.2 / Round 2a task 2 — write docs/data/extraction/*.sql.

    python3 scripts/generate_extraction_sql.py [--cohort data/real/cohort.txt]
                                               [--out docs/data/extraction]

Round 2a: the cohort is the FIRM (5,746 advisors) and the in-scope account set
is ~3M keys — NEITHER is ever inlined into an IN (...) list. Every session
starts with 00_session_setup.sql, which creates two TEMP tables:

  cohort_adv (advisor_sid)  — loaded from cohort.txt
  scoped_acct (k)           — every in-scope traded account key, computed ONCE
                              per session instead of re-scanning the 12.4M-row
                              trade table once per extract

and every template joins them. A temp table does NOT survive a reconnect, and
a token refresh IS a reconnect — scripts/extract_chunked.py re-runs the setup
on every connection automatically; a human running the .sql files by hand must
re-run 00_session_setup.sql after any reconnect.

The three account-scoped multi-million-row tables (raw_account,
raw_acct_eci_rel, raw_acct_eci_map) carry a /*BUCKET*/ marker where
extract_chunked.py injects `AND mod(abs(hashtext(s.k)), :n) = :b` to split
them into deterministic, resumable bucket chunks. raw_monthly_balance is
split BY MONTH (one query per month table — never one UNION).

Corrections baked in (ROUND_D_EXTRACTION.md §4, client-confirmed):
  - raw_acct_eci_map: source column IS new_exst_adv_clnt_in_cyr (no rename in SQL —
    build_real_data.py maps it to the graph's new_exst_adv_clnt_in);
    latest bus_dt per (wm_src_sys_cd, wm_acct_src_nb) only.
  - raw_monthly_balance: columns are acct_id, acct_bal (per-month files).
  - raw_advisor: includes transfer counterparties outside the cohort with
    in_cohort=false (or every transfer edge pointing at them drops at load).
  - raw_adv_flows: APRIL-JUNE (Round 2a: June flow rows now exist — 19,443,868
    daily rows across the three months aggregate to 166,985 output rows; the
    aggregate is what extracts, never the daily rows); other_attributes JSONB
    flattened into the six named columns.
  - raw_advisor_flags (Round 5 task 1): RETIRED — it existed only to score
    advisors for scripts/select_cohort.py's 20-advisor demo selection, and the
    client now DEFINES the cohort (scripts/build_cohort.py runs their query);
    nothing selects anything and nothing consumes the file.
  - cohort application (Round 5 task 1, client-mandated): the cohort is
    applied via ``advisor_sid IN (SELECT advisor_sid FROM cohort_adv)`` —
    NEVER a join. fpic_prm_rr_tb / fpic_employee_tb are reference tables with
    one row per branch/location; joining them to the trade table both drops
    unmatched rows and multiplies matched ones (the 4.1M-row loss).
  - month meta: expect 30/31/30 calendar days (the table accrues daily).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

HEADER = """-- GENERATED by scripts/generate_extraction_sql.py from {cohort_path}
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/{csv_name}
"""

# The date scope — one source of truth for every template.
SCOPE_START, SCOPE_END = "2026-04-01", "2026-07-01"

# The monthly balance tables, one per month — extracted per month, NEVER as
# one UNION (8.68M rows in a single query would not finish inside the 900s
# statement timeout).
BALANCE_TABLES = {
    "202604": "fpic_monthly_acct_balance_tb_april",
    "202605": "fpic_monthly_acct_balance_tb_may",
    "202606": "fpic_monthly_acct_balance_tb_june",
}

# Round 5 task 1: the ONE cohort-application line every scoped extract uses —
# IN (SELECT ...), NEVER a join (client-mandated; reference tables carry one
# row per branch/location, so a join fans out / drops rows — the 4.1M loss).
# extract_chunked.txn_chunk_sql swaps this exact line for a per-chunk batch.
TXN_COHORT_LINE = "  AND  d.advisor_sid IN (SELECT advisor_sid FROM cohort_adv)\n"

# Templates that carry the /*BUCKET*/ marker — extract_chunked.py splits each
# into --buckets deterministic chunks over scoped_acct's key hash.
BUCKETED_SQL = ("raw_account.sql", "raw_acct_eci_rel.sql", "raw_acct_eci_map.sql")

# The marker extract_chunked.py replaces. Kept as a constant so the assertion
# there and the templates here cannot drift apart.
BUCKET_MARKER = "/*BUCKET*/"


def bucket_predicate(n_buckets: int, bucket: int) -> str:
    """The deterministic, reproducible bucket split over the scoped account
    key. hashtext() is stable within a PostgreSQL major version, which is all
    a resumable extract needs (all buckets of a table come from one plan)."""
    return f"AND mod(abs(hashtext(s.k)), {n_buckets}) = {bucket}"


def session_setup_statements(sids: list[str]) -> list[str]:
    """The per-session temp-table setup as individual executable statements.
    cohort_adv is loaded by multi-row INSERTs (500 SIDs per statement — never
    one giant literal); scoped_acct is computed ONCE from the trade table."""
    stmts = ["CREATE TEMP TABLE cohort_adv (advisor_sid varchar(11) PRIMARY KEY)"]
    for i in range(0, len(sids), 500):
        values = ",".join(f"('{s}')" for s in sids[i:i + 500])
        stmts.append(f"INSERT INTO cohort_adv (advisor_sid) VALUES {values}")
    stmts.append(f"""CREATE TEMP TABLE scoped_acct AS
SELECT DISTINCT ltrim(trim(d.account_no),'0') AS k
FROM   pcr.fpic_daily_trade_details_tb_prod d
WHERE  d.trade_dt >= DATE '{SCOPE_START}' AND d.trade_dt < DATE '{SCOPE_END}'
  AND  d.advisor_sid IN (SELECT advisor_sid FROM cohort_adv)""")
    stmts.append("CREATE INDEX ON scoped_acct (k)")
    stmts.append("ANALYZE scoped_acct")
    return stmts


def session_setup_sql(sids: list[str], cohort_path: str = "data/real/cohort.txt") -> str:
    """00_session_setup.sql for a human session. States the reconnect rule."""
    return (
        "-- 00_session_setup.sql — run at the START of EVERY database session,\n"
        "-- BEFORE any extract. A temp table does not survive a reconnect, and a\n"
        "-- token refresh IS a reconnect: after any re-auth, run this again.\n"
        f"-- (psql alternative for cohort_adv: \\copy cohort_adv FROM '{cohort_path}')\n"
        "SET statement_timeout = '600s';\n\n"
        + ";\n\n".join(session_setup_statements(sids)) + ";\n"
    )


def monthly_balance_sql(month_id: str) -> str:
    """One month's balance extract — its own query, its own CSV
    (raw_balance_<month>.csv). Joins scoped_acct; never a UNION."""
    table = BALANCE_TABLES.get(month_id)
    if table is None:
        raise KeyError(
            f"no balance table known for month {month_id} — extend "
            f"BALANCE_TABLES in scripts/generate_extraction_sql.py (known: "
            f"{sorted(BALANCE_TABLES)})")
    return f"""
-- Month-end balances for {month_id}: columns confirmed acct_id / acct_bal.
-- ONE month per query (never a UNION — 8.68M rows in one statement will not
-- finish inside the 900s timeout). Requires 00_session_setup.sql this session.
SELECT '{month_id}' AS month_id, b.acct_id, b.acct_bal
FROM   pcr.{table} b
JOIN   scoped_acct s ON s.k = ltrim(trim(b.acct_id),'0');
"""


def templates(sids: list[str] | None = None) -> dict[str, str]:
    """Every extract's SQL. Round 2a: NO SID or account-key list is inlined —
    the templates join the session temp tables from session_setup_statements()
    (the sids parameter is kept for call compatibility; the setup owns them).
    The transaction template's cohort IN-line (TXN_COHORT_LINE — never a
    join) is swapped for a per-chunk advisor batch by
    extract_chunked.txn_chunk_sql()."""
    return {
        "raw_advisor.sql": f"""
-- Cohort advisors (in_cohort=true) PLUS every transfer counterparty
-- (in_cohort=false) — miss them and every transfer edge pointing at them
-- drops silently at load. Blank names stay blank; never invent one.
-- job_code (Round 1b): fpic_employee_tb.job_cd, carried for plan
-- eligibility. Round 5: em_status_cd / em_work_st_cd / em_work_city_txt
-- added (client requirements 17 Aug). No employee row -> blank; a blank
-- stays blank. DISTINCT ON collapses fpic_prm_rr_tb's one-row-per-branch
-- fan-out to ONE row per advisor (the client's reference-table warning).
WITH cohort(advisor_sid) AS (
  SELECT advisor_sid FROM cohort_adv
),
counterparties AS (
  SELECT DISTINCT c.from_mem_sid AS advisor_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '{SCOPE_START}' AND c.transfer_ts < DATE '{SCOPE_END}'
    AND  c.to_mem_sid IN (SELECT advisor_sid FROM cohort)
  UNION
  SELECT DISTINCT c.to_mem_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '{SCOPE_START}' AND c.transfer_ts < DATE '{SCOPE_END}'
    AND  c.from_mem_sid IN (SELECT advisor_sid FROM cohort)
)
SELECT DISTINCT ON (r.standard_id)
       r.standard_id                              AS advisor_sid,
       r.prm_rr_no                                AS rep_code,
       COALESCE(e.em_name_txt,'')                 AS advisor_name,
       r.cwm_branch_cd                            AS branch_cd,
       COALESCE(e.em_standard_id,'')              AS employee_id,
       (r.standard_id IN (SELECT advisor_sid FROM cohort)) AS in_cohort,
       COALESCE(e.job_cd,'')                      AS job_code,
       COALESCE(e.em_status_cd,'')                AS em_status_cd,
       COALESCE(e.em_work_st_cd,'')               AS em_work_st_cd,
       COALESCE(e.em_work_city_txt,'')            AS em_work_city_txt
FROM   pcr.fpic_prm_rr_tb r
LEFT   JOIN pcr.fpic_employee_tb e ON e.em_standard_id = r.standard_id
WHERE  r.standard_id IN (SELECT advisor_sid FROM cohort)
   OR  r.standard_id IN (SELECT advisor_sid FROM counterparties)
ORDER  BY r.standard_id;
""",
        "raw_account.sql": f"""
-- Accounts with in-scope cohort trades. Current snapshot — do NOT extract
-- financial_advisor_cd (no date column; historical attribution mis-assigns).
-- No PII columns, ever. Joins the session scoped_acct temp table (2.2);
-- {BUCKET_MARKER} is replaced by extract_chunked.py's bucket predicate.
SELECT DISTINCT
       a.account_number                           AS account_no,
       a.account_class_cd, a.account_class_nm, a.account_lob_cd,
       a.account_purpose_cd, a.managed_platform_cd, a.service_channel_cd,
       COALESCE(to_char(to_timestamp(NULLIF(trim(a.account_open_dt),''),
                                     'MM/DD/YYYY HH12:MI:SS AM'),
                        'YYYY-MM-DD HH24:MI:SS'),'') AS account_open_dt,
       COALESCE(a.party_primary_eci,'')           AS primary_eci_id
FROM   pcr.fpic_acct_tb_pm a
JOIN   scoped_acct s ON s.k = ltrim(trim(a.account_number),'0')
WHERE  1=1 {BUCKET_MARKER};
""",
        "raw_product_hierarchy.sql": """
-- Product taxonomy. grid_type pulled as a column; build filters PRODUCT_TYPE.
-- Round 1b: the two pay-type columns are a parallel snake_case taxonomy,
-- carried on the product vertex alongside the display grouping.
SELECT DISTINCT
       h.product_code                             AS product_cd,
       COALESCE(h.sub_product_code,'')            AS product_sub_cd,
       h.level_two_product                        AS product_name,
       h.level_one_product                        AS sor,
       ''                                         AS file_key,
       h.grid_type,
       COALESCE(h.level_one_pay_type_product_cd,'') AS l1_pay_type_cd,
       COALESCE(h.level_two_pay_type_product_cd,'') AS l2_pay_type_cd
FROM   pcr.product_hierarchy h;
""",
        "raw_revenue_transaction.sql": f"""
-- THE 48M-ROW TABLE: filter to cohort + date range BEFORE anything else or it
-- times out. Credited revenue = post_split_credited_amt (pre_split x split_pct
-- double-counts across advisors). NEVER join fpic_team_agreement_tb here.
-- Cohort applied via an IN-subquery on the session cohort temp table —
-- NEVER a join to the reference tables (Round 5, client-mandated: the
-- 4.1M-row loss). extract_chunked.py swaps that line for a per-chunk batch.
SELECT d.trade_ref_no, d.split_seq_no, d.advisor_sid,
       d.account_no, d.product_cd, d.product_sub_cd,
       d.trade_dt, d.proc_dt,
       d.post_split_credited_amt, d.pre_split_credited_amt, d.split_pct,
       COALESCE(NULLIF(trim(d.reason_cd),''),'') AS reason_cd,
       d.standard_rate_bps, d.client_rate_bps,
       d.discount_amt, d.eff_disc_pct, d.grid_reduction,
       COALESCE(d.rpg,'')                        AS rpg,
       COALESCE(d.concession_type,'')            AS concession_type,
       COALESCE(d.file_key,'')                   AS file_key,
       COALESCE(d.trade_description,'')          AS trade_description
FROM   pcr.fpic_daily_trade_details_tb_prod d
WHERE  d.trade_dt >= DATE '{SCOPE_START}'
  AND  d.trade_dt <  DATE '{SCOPE_END}'
{TXN_COHORT_LINE.rstrip()};
""",
        "raw_rr_changes.sql": f"""
-- Account transfers touching a cohort advisor, in scope.
SELECT c.occd_cd, c.account_no, c.transfer_ts, c.seq_no,
       c.from_rr, c.from_mem_sid, c.to_rr, c.to_mem_sid
FROM   pcr.fpic_rr_changes_from_nacs_logs c
WHERE  c.transfer_ts >= DATE '{SCOPE_START}' AND c.transfer_ts < DATE '{SCOPE_END}'
  AND  (c.from_mem_sid IN (SELECT advisor_sid FROM cohort_adv)
   OR   c.to_mem_sid   IN (SELECT advisor_sid FROM cohort_adv));
""",
        "raw_month_meta.sql": f"""
-- Month meta: trading_days = distinct trade dates. The table accrues DAILY
-- (weekends have rows), so expect calendar-day counts 30 / 31 / 30 and
-- is_partial=false for all three months (client Phase 0 confirmed June complete).
SELECT to_char(d.trade_dt,'YYYYMM')              AS month_id,
       to_char(date_trunc('month', min(d.trade_dt)),'YYYY-MM-DD HH24:MI:SS') AS start_dt,
       to_char(max(d.trade_dt),'YYYY-MM-DD HH24:MI:SS')                      AS end_dt,
       count(DISTINCT d.trade_dt)                AS trading_days
FROM   pcr.fpic_daily_trade_details_tb_prod d
WHERE  d.trade_dt >= DATE '{SCOPE_START}' AND d.trade_dt < DATE '{SCOPE_END}'
  AND  d.advisor_sid IN (SELECT advisor_sid FROM cohort_adv)
GROUP  BY 1 ORDER BY 1;
""",
        "raw_acct_eci_rel.sql": f"""
-- Account <-> household party, ALL relationship codes (incl. 802 Beneficiary).
-- Joins the session scoped_acct temp table; {BUCKET_MARKER} is replaced by
-- extract_chunked.py's bucket predicate (6.97M rows never run as one query).
SELECT r.account_number, r.party_eci_id, r.enterprise_relationship_code,
       COALESCE(r.party_role_name,'')            AS party_role_name,
       COALESCE(r.client_employee_ind,'')        AS client_employee_ind
FROM   pcr.fpic_acct_eci_rel_tb_pm r
JOIN   scoped_acct s ON s.k = ltrim(trim(r.account_number),'0')
WHERE  1=1 {BUCKET_MARKER};
""",
        "raw_acct_eci_map.sql": f"""
-- Cross-system account <-> ECI map. DAILY SNAPSHOT: latest bus_dt per
-- (wm_src_sys_cd, wm_acct_src_nb) only. Source column IS
-- new_exst_adv_clnt_in_cyr — the graph column has no _cyr; build_real_data.py
-- does the rename. bus_dt is varchar; cast it. Joins scoped_acct;
-- {BUCKET_MARKER} is replaced by extract_chunked.py's bucket predicate — the
-- window function then ranks only the bucket's keys, never all 12.6M rows.
WITH ranked AS (
  SELECT m.bus_dt, m.wm_src_sys_cd, m.wm_acct_src_nb, m.eci_nb,
         m.new_exst_adv_clnt_in_cyr,
         row_number() OVER (PARTITION BY m.wm_src_sys_cd, m.wm_acct_src_nb
                            ORDER BY m.bus_dt::date DESC) AS rn
  FROM   pcr.fpic_acct_eci_map_tb m
  JOIN   scoped_acct s ON s.k = ltrim(trim(m.wm_acct_src_nb),'0')
  WHERE  1=1 {BUCKET_MARKER}
)
SELECT bus_dt, wm_src_sys_cd, wm_acct_src_nb, eci_nb, new_exst_adv_clnt_in_cyr
FROM   ranked WHERE rn = 1;
""",
        "raw_team_agreement.sql": f"""
-- Team splits — REFERENCE DATA ONLY. Never joined to trades
-- (post_split_credited_amt already carries the split; the join fans out one
-- row per secondary member). Shares stay as fractions 0.0-1.0.
SELECT t.agreement_id, t.team_rep_cd, t.team_agreement_typ,
       t.team_agreement_status_cd,
       t.prm_standard_id, t.prm_share_pct, t.sec_standard_id, t.sec_share_pct,
       t.start_ts, t.end_ts
FROM   pcr.fpic_team_agreement_tb t
WHERE  (t.prm_standard_id IN (SELECT advisor_sid FROM cohort_adv)
   OR   t.sec_standard_id IN (SELECT advisor_sid FROM cohort_adv))
  AND  t.start_ts < DATE '{SCOPE_END}'
  AND  (t.end_ts IS NULL OR t.end_ts >= DATE '{SCOPE_START}');
""",
        "raw_adv_flows.sql": f"""
-- Advisor flows: APRIL-JUNE (Round 2a — June flow rows now exist; the earlier
-- April/May-only finding no longer holds). 19,443,868 daily rows aggregate to
-- an expected 166,985 output rows — THE AGGREGATE IS WHAT EXTRACTS; the daily
-- rows never cross the wire. other_attributes JSONB flattened into the six
-- named columns — 0 / empty where absent.
SELECT r.standard_id                             AS advisor_sid,
       to_char(f.bus_dt::date,'YYYYMM')          AS month_id,
       f.cwm_flow_comp_prod_cd                   AS flow_product_cd,
       COALESCE(f.cwm_flow_comp_prod_desc_tx,'') AS flow_product_desc,
       COALESCE(f.cwm_comp_group_type,'')        AS comp_group_type,
       sum(COALESCE(f.total_inflows_am,0))       AS total_inflows,
       sum(COALESCE(f.total_outflows_am,0))      AS total_outflows,
       sum(COALESCE(f.total_net_financial_flows,0))          AS total_net_flows,
       sum(COALESCE(f.total_cwm_comp_credited_flows_am,0))   AS credited_flows,
       max(COALESCE(f.other_attributes->>'departed_advisor_sid',''))       AS departed_advisor_sid,
       sum(COALESCE((f.other_attributes->>'departed_advisor_excl_am')::numeric,0))   AS departed_advisor_excl_am,
       sum(COALESCE((f.other_attributes->>'lob_trfr_excl_am')::numeric,0))           AS lob_trfr_excl_am,
       sum(COALESCE((f.other_attributes->>'oi_pa_referral_cap_adj_am')::numeric,0))  AS oi_pa_referral_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'large_flow_cap_adj_am')::numeric,0))      AS large_flow_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'forced_closure_excl_am')::numeric,0))     AS forced_closure_excl_am
FROM   pcr.fpic_daily_adv_flows_tb_pm f
-- rep-code -> SID resolution needs fpic_prm_rr_tb, but that reference table
-- carries ONE ROW PER BRANCH (client, 17 Aug) — the DISTINCT subselect
-- collapses it to one row per (standard_id, prm_rr_no) so the join can
-- never multiply flow rows.
JOIN   (SELECT DISTINCT standard_id, prm_rr_no FROM pcr.fpic_prm_rr_tb) r
       ON r.standard_id = f.rep_wrkr_sid OR r.prm_rr_no = f.pri_rep_cd
WHERE  f.bus_dt::date >= DATE '{SCOPE_START}' AND f.bus_dt::date < DATE '{SCOPE_END}'
  AND  r.standard_id IN (SELECT advisor_sid FROM cohort_adv)
GROUP  BY 1, 2, 3, 4, 5;
""",
        "raw_crm_opportunity.sql": """
-- Round F2: the CRM opportunity extract, COHORT-FILTERED. At firm scale the
-- delivered flat file (crm_opportunities.csv, 308,534 rows) usually replaces
-- this SQL — build_real_data.py filters it to in-scope advisors/ECIs and
-- reports the out-of-scope count. Table located via
-- docs/data/extraction/discovery_crm_amount.sql STEP 0; replace <crm_table>
-- with the schema-qualified name it returned.
-- Invalid advisor references (e.g. 'I817209_CWM_INVALID') are INCLUDED on
-- purpose — build_real_data.py strips the suffix, keeps the raw value, sets
-- advisor_valid=false and REPORTS the count. Never filter them out here.
-- The eci__c half of the filter keeps opportunities on cohort households
-- whose owner sid is invalid or missing.
SELECT o.id                                    AS opportunity_id,
       COALESCE(o.eci__c,'')                   AS eci_id,
       COALESCE(o.ownersid__c,'')              AS ownersid,
       COALESCE(o.account_record_type_name__c,'') AS account_record_type,
       COALESCE(o.product_service_type__c,'')  AS product_service_type,
       COALESCE(o.stagename,'')                AS stage_name,
       COALESCE(o.amount,0)                    AS amount,
       COALESCE(o.actual_assets__c,0)          AS actual_assets,
       o.anticipated_investment_date__c        AS anticipated_investment_dt,
       o.createddate                           AS created_dt,
       o.lastmodifieddate                      AS last_modified_dt,
       o.date_of_last_contact__c               AS date_of_last_contact,
       COALESCE(o.days_to_close,0)             AS days_to_close,
       COALESCE(o.additional_comments__c,'')   AS comments
FROM   <crm_table> o
WHERE  regexp_replace(COALESCE(o.ownersid__c,''), '_.*$', '')
         IN (SELECT advisor_sid FROM cohort_adv)
   OR  o.eci__c IN (
         SELECT DISTINCT r.party_eci_id
         FROM   pcr.fpic_acct_eci_rel_tb_pm r
         JOIN   scoped_acct s ON s.k = ltrim(trim(r.account_number),'0')
       );
""",
    }
    # NOTE (Round F2): the four NNM files (ECNNM_/NBNNM_/YINNM_/FSNNM_*.txt)
    # are DELIVERED FILES, not SQL extracts — there is no SQL template for
    # them. Drop them into data/real/_raw/ as received; scripts/parse_nnm.py
    # reads the pipe-delimited format directly (H header line, D-prefixed
    # dates, negatives preserved).


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cohort", default="data/real/cohort.txt")
    ap.add_argument("--out", default="docs/data/extraction")
    args = ap.parse_args()

    cohort_path = Path(args.cohort)
    if not cohort_path.exists():
        print(f"ERROR: {cohort_path} not found — write one advisor_sid per line "
              f"(the full book from the sizing query)", file=sys.stderr)
        return 1
    sids = [ln.strip() for ln in cohort_path.read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.startswith("#")]
    if not sids:
        print(f"ERROR: {cohort_path} contains no advisor SIDs", file=sys.stderr)
        return 1
    print(f"cohort: {len(sids)} advisors from {cohort_path}")

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "00_session_setup.sql").write_text(
        session_setup_sql(sids, str(cohort_path)), encoding="utf-8")
    print(f"wrote {out / '00_session_setup.sql'}")
    for fname, body in templates(sids).items():
        csv_name = fname.replace(".sql", ".csv")
        text = HEADER.format(cohort_path=cohort_path, csv_name=csv_name) + body.lstrip("\n")
        (out / fname).write_text(text, encoding="utf-8")
        print(f"wrote {out / fname}")
    for month_id in BALANCE_TABLES:
        fname = f"raw_balance_{month_id}.sql"
        text = HEADER.format(cohort_path=cohort_path,
                             csv_name=f"raw_balance_{month_id}.csv") \
            + monthly_balance_sql(month_id).lstrip("\n")
        (out / fname).write_text(text, encoding="utf-8")
        print(f"wrote {out / fname}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
