-- HAND-AUTHORED one-off discovery query (Round F2 Task 1.1) — NOT generated by
-- scripts/generate_extraction_sql.py; independent of the cohort.
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
--
-- QUESTION THIS ANSWERS: does a job code column exist on the employee/RR
-- tables? The Select Advisor Group Plan (SAG p.9) makes plan eligibility
-- depend on job code — HK0176, HK0186, HK0187, HK0188 -> CWM Select Advisor.
-- V2 only ever read em_standard_id and em_name_txt; the full column lists of
-- these two tables have never been observed.
--
-- HOW TO READ THE RESULT:
--   * If a column that plausibly carries a job code exists (job_code,
--     job_cd, jobcode, hr_job_cd, position_cd, ...), paste the full output
--     back and we add `job_code` to phx_dm_pce_advisor and raw_advisor.sql —
--     plan applicability then becomes derivable per advisor.
--   * If no such column exists, plan applicability cannot be derived from
--     these tables and the client must tell us where job codes live
--     (HR feed? a different pcr table?). Until then every rule applies to
--     every advisor, which is WRONG for a firm running two different plans —
--     this is a standing client question, not something we guess.

SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema='pcr'
  AND table_name IN ('fpic_employee_tb','fpic_prm_rr_tb')
ORDER BY table_name, ordinal_position;

-- If a candidate column is found, profile it before we wire anything:
-- (replace <job_code_col> and <table> with what the query above showed)
--
-- SELECT <job_code_col>, count(*)
-- FROM pcr.<table>
-- GROUP BY 1 ORDER BY 2 DESC LIMIT 50;
--
-- We expect to see HK0176 / HK0186 / HK0187 / HK0188 among the values if this
-- is the plan-eligibility code (SAG p.9).
