-- HAND-AUTHORED one-off discovery query (Round F2 Task 1.2) — NOT generated by
-- scripts/generate_extraction_sql.py; independent of the cohort.
-- Run manually against PostgreSQL db fpicdb (IAM token auth; on PAM/auth
-- failure the token expired: aws sts get-caller-identity, refresh SSO, retry).
-- ALWAYS run first:  SET statement_timeout = '600s';
--
-- QUESTION THIS ANSWERS: what do `amount` and `actual_assets__c` actually
-- mean on the CRM opportunity extract? Observed so far (sample of
-- 45f440b6-be31-4d2a-b3e4-9843d539b408.csv, 308,534 rows): amount = 0 in
-- every sampled row while actual_assets__c carries 100 .. 5,000,000; the
-- operator reports amount ranges -1 to 2 billion over the full file.
--
-- STEP 0 — the CRM table name is not yet known (the extract arrived as a CSV
-- with a UUID filename). Locate it by its distinctive Salesforce columns:

SELECT table_schema, table_name
FROM information_schema.columns
WHERE column_name IN ('ownersid__c','eci__c','actual_assets__c')
GROUP BY 1, 2
HAVING count(DISTINCT column_name) = 3;

-- STEP 1 — profile amount vs actual_assets__c by stage
-- (replace <crm_table> with the schema-qualified name STEP 0 returned):

SELECT stagename, count(*) AS rows,
       count(*) FILTER (WHERE amount <> 0)          AS has_amount,
       count(*) FILTER (WHERE actual_assets__c > 0) AS has_actual,
       round(avg(amount))            AS avg_amount,
       round(avg(actual_assets__c))  AS avg_actual
FROM <crm_table> GROUP BY 1 ORDER BY 2 DESC;

-- STEP 2 — do the two fields ever coexist on one row?

SELECT count(*) FROM <crm_table> WHERE amount <> 0 AND actual_assets__c > 0;

-- STEP 3 — negative amounts exist per the operator (-1 .. 2bn); size them:

SELECT count(*) FILTER (WHERE amount < 0)  AS neg_amount_rows,
       min(amount) AS min_amount, max(amount) AS max_amount,
       count(*) FILTER (WHERE actual_assets__c < 0) AS neg_actual_rows
FROM <crm_table>;

-- HOW TO READ THE RESULT — the WORKING INTERPRETATION until the client
-- confirms (recorded as an assumption in docs/DECISIONS.md):
--   * amount            = the Salesforce standard opportunity Amount — the
--                         FORECAST pipeline value
--   * actual_assets__c  = a custom field (the __c suffix marks it), added
--                         because standard Amount did not capture what the
--                         business needed — the assets that ACTUALLY LANDED
--   * NEVER sum the two — they describe the same opportunity and summing
--     them double-counts it.
-- If STEP 1 shows has_amount concentrated in early stages and has_actual in
-- late/closing stages, the interpretation holds. If both are populated on the
-- same rows at scale (STEP 2 large), the interpretation is wrong — stop and
-- ask the client which field "opportunity value" means.
