-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_acct_eci_map.csv
-- Cross-system account <-> ECI map. DAILY SNAPSHOT: latest bus_dt per
-- (wm_src_sys_cd, wm_acct_src_nb) only. Source column IS
-- new_exst_adv_clnt_in_cyr — the graph column has no _cyr; build_real_data.py
-- does the rename. bus_dt is varchar; cast it. Joins scoped_acct;
-- /*BUCKET*/ is replaced by extract_chunked.py's bucket predicate — the
-- window function then ranks only the bucket's keys, never all 12.6M rows.
WITH ranked AS (
  SELECT m.bus_dt, m.wm_src_sys_cd, m.wm_acct_src_nb, m.eci_nb,
         m.new_exst_adv_clnt_in_cyr,
         row_number() OVER (PARTITION BY m.wm_src_sys_cd, m.wm_acct_src_nb
                            ORDER BY m.bus_dt::date DESC) AS rn
  FROM   pcr.fpic_acct_eci_map_tb m
  JOIN   scoped_acct s ON s.k = ltrim(trim(m.wm_acct_src_nb),'0')
  WHERE  1=1 /*BUCKET*/
)
SELECT bus_dt, wm_src_sys_cd, wm_acct_src_nb, eci_nb, new_exst_adv_clnt_in_cyr
FROM   ranked WHERE rn = 1;
