-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_acct_eci_rel.csv
-- Account <-> household party, ALL relationship codes (incl. 802 Beneficiary).
-- Joins the session scoped_acct temp table; /*BUCKET*/ is replaced by
-- extract_chunked.py's bucket predicate (6.97M rows never run as one query).
SELECT r.account_number, r.party_eci_id, r.enterprise_relationship_code,
       COALESCE(r.party_role_name,'')            AS party_role_name,
       COALESCE(r.client_employee_ind,'')        AS client_employee_ind
FROM   pcr.fpic_acct_eci_rel_tb_pm r
JOIN   scoped_acct s ON s.k = ltrim(trim(r.account_number),'0')
WHERE  1=1 /*BUCKET*/;
