-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_team_agreement.csv
-- Team splits — REFERENCE DATA ONLY. Never joined to trades
-- (post_split_credited_amt already carries the split; the join fans out one
-- row per secondary member). Shares stay as fractions 0.0-1.0.
SELECT t.agreement_id, t.team_rep_cd, t.team_agreement_typ,
       t.team_agreement_status_cd,
       t.prm_standard_id, t.prm_share_pct, t.sec_standard_id, t.sec_share_pct,
       t.start_ts, t.end_ts
FROM   pcr.fpic_team_agreement_tb t
WHERE  (t.prm_standard_id IN (SELECT advisor_sid FROM cohort_adv)
   OR   t.sec_standard_id IN (SELECT advisor_sid FROM cohort_adv))
  AND  t.start_ts < DATE '2026-07-01'
  AND  (t.end_ts IS NULL OR t.end_ts >= DATE '2026-04-01');
