-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_revenue_transaction.csv
-- THE 48M-ROW TABLE: filter to cohort + date range BEFORE anything else or it
-- times out. Credited revenue = post_split_credited_amt (pre_split x split_pct
-- double-counts across advisors). NEVER join fpic_team_agreement_tb here.
-- Cohort applied via IN (SELECT ... FROM cohort_adv) — NEVER a join to the
-- reference tables (Round 5, client-mandated: the 4.1M-row loss).
-- extract_chunked.py swaps the cohort line for a per-chunk advisor batch.
SELECT d.trade_ref_no, d.split_seq_no, d.advisor_sid,
       d.account_no, d.product_cd, d.product_sub_cd,
       d.trade_dt, d.proc_dt,
       d.post_split_credited_amt, d.pre_split_credited_amt, d.split_pct,
       COALESCE(NULLIF(trim(d.reason_cd),''),'') AS reason_cd,
       d.standard_rate_bps, d.client_rate_bps,
       d.discount_amt, d.eff_disc_pct, d.grid_reduction,
       COALESCE(d.rpg,'')                        AS rpg,
       COALESCE(d.concession_type,'')            AS concession_type,
       COALESCE(d.file_key,'')                   AS file_key,
       COALESCE(d.trade_description,'')          AS trade_description
FROM   pcr.fpic_daily_trade_details_tb_prod d
WHERE  d.trade_dt >= DATE '2026-04-01'
  AND  d.trade_dt <  DATE '2026-07-01'
  AND  d.advisor_sid IN (SELECT advisor_sid FROM cohort_adv);
