-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_crm_opportunity.csv
-- Round F2: the CRM opportunity extract, COHORT-FILTERED. At firm scale the
-- delivered flat file (crm_opportunities.csv, 308,534 rows) usually replaces
-- this SQL — build_real_data.py filters it to in-scope advisors/ECIs and
-- reports the out-of-scope count. Table located via
-- docs/data/extraction/discovery_crm_amount.sql STEP 0; replace <crm_table>
-- with the schema-qualified name it returned.
-- Invalid advisor references (e.g. 'I817209_CWM_INVALID') are INCLUDED on
-- purpose — build_real_data.py strips the suffix, keeps the raw value, sets
-- advisor_valid=false and REPORTS the count. Never filter them out here.
-- The eci__c half of the filter keeps opportunities on cohort households
-- whose owner sid is invalid or missing.
SELECT o.id                                    AS opportunity_id,
       COALESCE(o.eci__c,'')                   AS eci_id,
       COALESCE(o.ownersid__c,'')              AS ownersid,
       COALESCE(o.account_record_type_name__c,'') AS account_record_type,
       COALESCE(o.product_service_type__c,'')  AS product_service_type,
       COALESCE(o.stagename,'')                AS stage_name,
       COALESCE(o.amount,0)                    AS amount,
       COALESCE(o.actual_assets__c,0)          AS actual_assets,
       o.anticipated_investment_date__c        AS anticipated_investment_dt,
       o.createddate                           AS created_dt,
       o.lastmodifieddate                      AS last_modified_dt,
       o.date_of_last_contact__c               AS date_of_last_contact,
       COALESCE(o.days_to_close,0)             AS days_to_close,
       COALESCE(o.additional_comments__c,'')   AS comments
FROM   <crm_table> o
WHERE  regexp_replace(COALESCE(o.ownersid__c,''), '_.*$', '')
         IN (SELECT advisor_sid FROM cohort_adv)
   OR  o.eci__c IN (
         SELECT DISTINCT r.party_eci_id
         FROM   pcr.fpic_acct_eci_rel_tb_pm r
         JOIN   scoped_acct s ON s.k = ltrim(trim(r.account_number),'0')
       );
