-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_balance_202604.csv
-- Month-end balances for 202604: columns confirmed acct_id / acct_bal.
-- ONE month per query (never a UNION — 8.68M rows in one statement will not
-- finish inside the 900s timeout). Requires 00_session_setup.sql this session.
SELECT '202604' AS month_id, b.acct_id, b.acct_bal
FROM   pcr.fpic_monthly_acct_balance_tb_april b
JOIN   scoped_acct s ON s.k = ltrim(trim(b.acct_id),'0');
