-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_advisor.csv
-- Cohort advisors (in_cohort=true) PLUS every transfer counterparty
-- (in_cohort=false) — miss them and every transfer edge pointing at them
-- drops silently at load. Blank names stay blank; never invent one.
WITH cohort(advisor_sid) AS (
  SELECT unnest(ARRAY['T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017'])
),
counterparties AS (
  SELECT DISTINCT c.from_mem_sid AS advisor_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
    AND  c.to_mem_sid IN (SELECT advisor_sid FROM cohort)
  UNION
  SELECT DISTINCT c.to_mem_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
    AND  c.from_mem_sid IN (SELECT advisor_sid FROM cohort)
)
SELECT r.standard_id                              AS advisor_sid,
       r.prm_rr_no                                AS rep_code,
       COALESCE(e.em_name_txt,'')                 AS advisor_name,
       r.cwm_branch_cd                            AS branch_cd,
       COALESCE(e.em_standard_id,'')              AS employee_id,
       (r.standard_id IN (SELECT advisor_sid FROM cohort)) AS in_cohort
FROM   pcr.fpic_prm_rr_tb r
LEFT   JOIN pcr.fpic_employee_tb e ON e.em_standard_id = r.standard_id
WHERE  r.standard_id IN (SELECT advisor_sid FROM cohort)
   OR  r.standard_id IN (SELECT advisor_sid FROM counterparties);
