-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_monthly_balance.csv
-- Month-end balances: columns confirmed acct_id / acct_bal. Three month tables
-- unioned with an explicit month_id. Restricted to cohort-traded accounts.
WITH cohort_accts AS (
  SELECT DISTINCT ltrim(trim(d.account_no),'0') AS acct_key
  FROM   pcr.fpic_daily_trade_details_tb_prod d
  WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
    AND  d.advisor_sid IN ('T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017')
)
SELECT '202604' AS month_id, b.acct_id, b.acct_bal
FROM   pcr.fpic_monthly_acct_balance_tb_april b
WHERE  ltrim(trim(b.acct_id),'0') IN (SELECT acct_key FROM cohort_accts)
UNION ALL
SELECT '202605', b.acct_id, b.acct_bal
FROM   pcr.fpic_monthly_acct_balance_tb_may b
WHERE  ltrim(trim(b.acct_id),'0') IN (SELECT acct_key FROM cohort_accts)
UNION ALL
SELECT '202606', b.acct_id, b.acct_bal
FROM   pcr.fpic_monthly_acct_balance_tb_june b
WHERE  ltrim(trim(b.acct_id),'0') IN (SELECT acct_key FROM cohort_accts);
