-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_advisor_flags.csv
-- Step 1, run FIRST (feeds scripts/select_cohort.py — no cohort filter yet).
-- Scores every advisor with in-scope trades on the nine scenario flags.
-- grid_reduction is SCARCE (~99 accounts firmwide) — the selector takes it first.
WITH scoped AS (
  SELECT d.advisor_sid, d.account_no, d.post_split_credited_amt, d.reason_cd,
         d.standard_rate_bps, d.client_rate_bps, d.grid_reduction
  FROM   pcr.fpic_daily_trade_details_tb_prod d
  WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
)
SELECT s.advisor_sid,
       max(r.prm_rr_no)                          AS rep_code,
       max(e.em_name_txt)                        AS advisor_name,
       sum(CASE WHEN COALESCE(NULLIF(trim(s.reason_cd),''),'__NONE__') = '__NONE__'
                THEN s.post_split_credited_amt ELSE 0 END) AS total_credited_amt,
       bool_or(s.standard_rate_bps > 0 AND
               (s.standard_rate_bps - s.client_rate_bps) / s.standard_rate_bps * 100 > 10)
                                                 AS has_fee_reduction_gt10,
       bool_or(COALESCE(s.grid_reduction,0) <> 0) AS has_recorded_grid_reduction,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_rr_changes_from_nacs_logs c
                       WHERE c.to_mem_sid = s.advisor_sid
                         AND c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'))
                                                 AS has_transfer_in,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_rr_changes_from_nacs_logs c
                       WHERE c.from_mem_sid = s.advisor_sid
                         AND c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'))
                                                 AS has_transfer_out,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_acct_tb_pm a
                       WHERE ltrim(trim(a.account_number),'0') = ltrim(trim(s.account_no),'0')
                         AND to_timestamp(NULLIF(trim(a.account_open_dt),''),
                                          'MM/DD/YYYY HH12:MI:SS AM')
                             >= DATE '2026-04-01'
                         AND to_timestamp(NULLIF(trim(a.account_open_dt),''),
                                          'MM/DD/YYYY HH12:MI:SS AM')
                             <  DATE '2026-07-01'))
                                                 AS has_new_account,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_monthly_acct_balance_tb_april b4
                       JOIN pcr.fpic_monthly_acct_balance_tb_may b5
                         ON ltrim(trim(b5.acct_id),'0') = ltrim(trim(b4.acct_id),'0')
                       WHERE ltrim(trim(b4.acct_id),'0') = ltrim(trim(s.account_no),'0')
                         AND b4.acct_bal > 0 AND b5.acct_bal = 0))
                                                 AS has_zeroed_account,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_team_agreement_tb t
                       WHERE (t.prm_standard_id = s.advisor_sid OR t.sec_standard_id = s.advisor_sid)
                         AND t.team_agreement_status_cd = 'ACTIVE'))
                                                 AS has_team_agreement,
       bool_or(EXISTS (SELECT 1 FROM pcr.fpic_daily_adv_flows_tb_pm f
                       WHERE f.rep_wrkr_sid = s.advisor_sid))
                                                 AS has_flows,
       bool_or(NULLIF(trim(s.reason_cd),'') IS NOT NULL)
                                                 AS has_non_credited
FROM   scoped s
JOIN   pcr.fpic_prm_rr_tb r ON r.standard_id = s.advisor_sid
LEFT   JOIN pcr.fpic_employee_tb e ON e.em_standard_id = s.advisor_sid
GROUP  BY s.advisor_sid;
