-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_adv_flows.csv
-- Advisor flows: APRIL AND MAY ONLY (no June rows exist). other_attributes
-- JSONB flattened into the six named columns — 0 / empty where absent.
SELECT r.standard_id                             AS advisor_sid,
       to_char(f.bus_dt::date,'YYYYMM')          AS month_id,
       f.cwm_flow_comp_prod_cd                   AS flow_product_cd,
       COALESCE(f.cwm_flow_comp_prod_desc_tx,'') AS flow_product_desc,
       COALESCE(f.cwm_comp_group_type,'')        AS comp_group_type,
       sum(COALESCE(f.total_inflows_am,0))       AS total_inflows,
       sum(COALESCE(f.total_outflows_am,0))      AS total_outflows,
       sum(COALESCE(f.total_net_financial_flows,0))          AS total_net_flows,
       sum(COALESCE(f.total_cwm_comp_credited_flows_am,0))   AS credited_flows,
       max(COALESCE(f.other_attributes->>'departed_advisor_sid',''))       AS departed_advisor_sid,
       sum(COALESCE((f.other_attributes->>'departed_advisor_excl_am')::numeric,0))   AS departed_advisor_excl_am,
       sum(COALESCE((f.other_attributes->>'lob_trfr_excl_am')::numeric,0))           AS lob_trfr_excl_am,
       sum(COALESCE((f.other_attributes->>'oi_pa_referral_cap_adj_am')::numeric,0))  AS oi_pa_referral_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'large_flow_cap_adj_am')::numeric,0))      AS large_flow_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'forced_closure_excl_am')::numeric,0))     AS forced_closure_excl_am
FROM   pcr.fpic_daily_adv_flows_tb_pm f
JOIN   pcr.fpic_prm_rr_tb r
       ON r.standard_id = f.rep_wrkr_sid OR r.prm_rr_no = f.pri_rep_cd
WHERE  f.bus_dt::date >= DATE '2026-04-01' AND f.bus_dt::date < DATE '2026-06-01'
  AND  r.standard_id IN ('T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017')
GROUP  BY 1, 2, 3, 4, 5;
