-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_account.csv
-- Accounts with in-scope cohort trades. Current snapshot — do NOT extract
-- financial_advisor_cd (no date column; historical attribution mis-assigns).
-- No PII columns, ever. Joins the session scoped_acct temp table (2.2);
-- /*BUCKET*/ is replaced by extract_chunked.py's bucket predicate.
SELECT DISTINCT
       a.account_number                           AS account_no,
       a.account_class_cd, a.account_class_nm, a.account_lob_cd,
       a.account_purpose_cd, a.managed_platform_cd, a.service_channel_cd,
       COALESCE(to_char(to_timestamp(NULLIF(trim(a.account_open_dt),''),
                                     'MM/DD/YYYY HH12:MI:SS AM'),
                        'YYYY-MM-DD HH24:MI:SS'),'') AS account_open_dt,
       COALESCE(a.party_primary_eci,'')           AS primary_eci_id
FROM   pcr.fpic_acct_tb_pm a
JOIN   scoped_acct s ON s.k = ltrim(trim(a.account_number),'0')
WHERE  1=1 /*BUCKET*/;
