-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_acct_eci_rel.csv
-- Account <-> household party, ALL relationship codes (incl. 802 Beneficiary).
SELECT r.account_number, r.party_eci_id, r.enterprise_relationship_code,
       COALESCE(r.party_role_name,'')            AS party_role_name,
       COALESCE(r.client_employee_ind,'')        AS client_employee_ind
FROM   pcr.fpic_acct_eci_rel_tb_pm r
WHERE  ltrim(trim(r.account_number),'0') IN (
         SELECT DISTINCT ltrim(trim(d.account_no),'0')
         FROM   pcr.fpic_daily_trade_details_tb_prod d
         WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
           AND  d.advisor_sid IN ('T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017')
       );
