-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_product_hierarchy.csv
-- Product taxonomy. grid_type pulled as a column; build filters PRODUCT_TYPE.
SELECT DISTINCT
       h.product_code                             AS product_cd,
       COALESCE(h.sub_product_code,'')            AS product_sub_cd,
       h.level_two_product                        AS product_name,
       h.level_one_product                        AS sor,
       ''                                         AS file_key,
       h.grid_type
FROM   pcr.product_hierarchy h;
