-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_rr_changes.csv
-- Account transfers touching a cohort advisor, in scope.
SELECT c.occd_cd, c.account_no, c.transfer_ts, c.seq_no,
       c.from_rr, c.from_mem_sid, c.to_rr, c.to_mem_sid
FROM   pcr.fpic_rr_changes_from_nacs_logs c
WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
  AND  (c.from_mem_sid IN ('T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017')
   OR   c.to_mem_sid   IN ('T000001','T000002','T000003','T000005','T000004',
                          'T000018','T000019','T000020','T000006','T000007',
                          'T000008','T000009','T000010','T000011','T000012',
                          'T000013','T000014','T000015','T000016','T000017'));
