-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_advisor_flags.csv
-- Per-advisor identity + credited total (contract columns for the build).
-- Round 2a: scenario-flag columns and their correlated EXISTS subqueries
-- REMOVED — they were a cohort-selection aid and the cohort is the firm.
SELECT s.advisor_sid,
       max(r.prm_rr_no)                          AS rep_code,
       max(e.em_name_txt)                        AS advisor_name,
       sum(CASE WHEN COALESCE(NULLIF(trim(s.reason_cd),''),'__NONE__') = '__NONE__'
                THEN s.post_split_credited_amt ELSE 0 END) AS total_credited_amt
FROM (
  SELECT d.advisor_sid, d.post_split_credited_amt, d.reason_cd
  FROM   pcr.fpic_daily_trade_details_tb_prod d
  JOIN   cohort_adv ca ON ca.advisor_sid = d.advisor_sid
  WHERE  d.trade_dt >= DATE '2026-04-01' AND d.trade_dt < DATE '2026-07-01'
) s
JOIN   pcr.fpic_prm_rr_tb r ON r.standard_id = s.advisor_sid
LEFT   JOIN pcr.fpic_employee_tb e ON e.em_standard_id = s.advisor_sid
GROUP  BY s.advisor_sid;
