-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_team_agreement.csv
-- Team splits — REFERENCE DATA ONLY. Never joined to trades
-- (post_split_credited_amt already carries the split; the join fans out one
-- row per secondary member). Shares stay as fractions 0.0-1.0.
SELECT t.agreement_id, t.team_rep_cd, t.team_agreement_typ,
       t.team_agreement_status_cd,
       t.prm_standard_id, t.prm_share_pct, t.sec_standard_id, t.sec_share_pct,
       t.start_ts, t.end_ts
FROM   pcr.fpic_team_agreement_tb t
WHERE  (t.prm_standard_id IN ('T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017')
   OR   t.sec_standard_id IN ('T000001','T000002','T000003','T000005','T000004',
                          'T000018','T000019','T000020','T000006','T000007',
                          'T000008','T000009','T000010','T000011','T000012',
                          'T000013','T000014','T000015','T000016','T000017'))
  AND  t.start_ts < DATE '2026-07-01'
  AND  (t.end_ts IS NULL OR t.end_ts >= DATE '2026-04-01');
