-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_adv_flows.csv
-- Advisor flows: APRIL-JUNE (Round 2a — June flow rows now exist; the earlier
-- April/May-only finding no longer holds). 19,443,868 daily rows aggregate to
-- an expected 166,985 output rows — THE AGGREGATE IS WHAT EXTRACTS; the daily
-- rows never cross the wire. other_attributes JSONB flattened into the six
-- named columns — 0 / empty where absent.
SELECT r.standard_id                             AS advisor_sid,
       to_char(f.bus_dt::date,'YYYYMM')          AS month_id,
       f.cwm_flow_comp_prod_cd                   AS flow_product_cd,
       COALESCE(f.cwm_flow_comp_prod_desc_tx,'') AS flow_product_desc,
       COALESCE(f.cwm_comp_group_type,'')        AS comp_group_type,
       sum(COALESCE(f.total_inflows_am,0))       AS total_inflows,
       sum(COALESCE(f.total_outflows_am,0))      AS total_outflows,
       sum(COALESCE(f.total_net_financial_flows,0))          AS total_net_flows,
       sum(COALESCE(f.total_cwm_comp_credited_flows_am,0))   AS credited_flows,
       max(COALESCE(f.other_attributes->>'departed_advisor_sid',''))       AS departed_advisor_sid,
       sum(COALESCE((f.other_attributes->>'departed_advisor_excl_am')::numeric,0))   AS departed_advisor_excl_am,
       sum(COALESCE((f.other_attributes->>'lob_trfr_excl_am')::numeric,0))           AS lob_trfr_excl_am,
       sum(COALESCE((f.other_attributes->>'oi_pa_referral_cap_adj_am')::numeric,0))  AS oi_pa_referral_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'large_flow_cap_adj_am')::numeric,0))      AS large_flow_cap_adj_am,
       sum(COALESCE((f.other_attributes->>'forced_closure_excl_am')::numeric,0))     AS forced_closure_excl_am
FROM   pcr.fpic_daily_adv_flows_tb_pm f
-- rep-code -> SID resolution needs fpic_prm_rr_tb, but that reference table
-- carries ONE ROW PER BRANCH (client, 17 Aug) — the DISTINCT subselect
-- collapses it to one row per (standard_id, prm_rr_no) so the join can
-- never multiply flow rows.
JOIN   (SELECT DISTINCT standard_id, prm_rr_no FROM pcr.fpic_prm_rr_tb) r
       ON r.standard_id = f.rep_wrkr_sid OR r.prm_rr_no = f.pri_rep_cd
WHERE  f.bus_dt::date >= DATE '2026-04-01' AND f.bus_dt::date < DATE '2026-07-01'
  AND  r.standard_id IN (SELECT advisor_sid FROM cohort_adv)
GROUP  BY 1, 2, 3, 4, 5;
