-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- THEN run 00_session_setup.sql (temp tables die with the session — a token
-- refresh is a reconnect, so re-run it after ANY reconnect).
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_advisor.csv
-- Cohort advisors (in_cohort=true) PLUS every transfer counterparty
-- (in_cohort=false) — miss them and every transfer edge pointing at them
-- drops silently at load. Blank names stay blank; never invent one.
-- job_code (Round 1b): fpic_employee_tb.job_cd, carried for plan
-- eligibility. Round 5: em_status_cd / em_work_st_cd / em_work_city_txt
-- added (client requirements 17 Aug). No employee row -> blank; a blank
-- stays blank. DISTINCT ON collapses fpic_prm_rr_tb's one-row-per-branch
-- fan-out to ONE row per advisor (the client's reference-table warning).
WITH cohort(advisor_sid) AS (
  SELECT advisor_sid FROM cohort_adv
),
counterparties AS (
  SELECT DISTINCT c.from_mem_sid AS advisor_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
    AND  c.to_mem_sid IN (SELECT advisor_sid FROM cohort)
  UNION
  SELECT DISTINCT c.to_mem_sid
  FROM   pcr.fpic_rr_changes_from_nacs_logs c
  WHERE  c.transfer_ts >= DATE '2026-04-01' AND c.transfer_ts < DATE '2026-07-01'
    AND  c.from_mem_sid IN (SELECT advisor_sid FROM cohort)
)
SELECT DISTINCT ON (r.standard_id)
       r.standard_id                              AS advisor_sid,
       r.prm_rr_no                                AS rep_code,
       COALESCE(e.em_name_txt,'')                 AS advisor_name,
       r.cwm_branch_cd                            AS branch_cd,
       COALESCE(e.em_standard_id,'')              AS employee_id,
       (r.standard_id IN (SELECT advisor_sid FROM cohort)) AS in_cohort,
       COALESCE(e.job_cd,'')                      AS job_code,
       COALESCE(e.em_status_cd,'')                AS em_status_cd,
       COALESCE(e.em_work_st_cd,'')               AS em_work_st_cd,
       COALESCE(e.em_work_city_txt,'')            AS em_work_city_txt
FROM   pcr.fpic_prm_rr_tb r
LEFT   JOIN pcr.fpic_employee_tb e ON e.em_standard_id = r.standard_id
WHERE  r.standard_id IN (SELECT advisor_sid FROM cohort)
   OR  r.standard_id IN (SELECT advisor_sid FROM counterparties)
ORDER  BY r.standard_id;
