-- GENERATED by scripts/generate_extraction_sql.py from data/real_test/cohort.txt
-- (do not edit by hand — edit the template in that script and regenerate).
-- Run manually against PostgreSQL db fpicdb, schema pcr (IAM token auth; on
-- PAM/auth failure the token expired: aws sts get-caller-identity, refresh SSO,
-- retry). ALWAYS run first:  SET statement_timeout = '600s';
-- Save the result as CSV (header row, comma, UTF-8): data/real/_raw/raw_crm_opportunity.csv
-- Round F2: the CRM opportunity extract, COHORT-FILTERED (the firm-wide file
-- is 308,534 rows — far more than a 20-advisor demo needs). Table located via
-- docs/data/extraction/discovery_crm_amount.sql STEP 0; replace <crm_table>
-- with the schema-qualified name it returned.
-- Invalid advisor references (e.g. 'I817209_CWM_INVALID') are INCLUDED on
-- purpose — build_real_data.py strips the suffix, keeps the raw value, sets
-- advisor_valid=false and REPORTS the count. Never filter them out here.
-- The eci__c half of the filter keeps opportunities on cohort households
-- whose owner sid is invalid or missing.
SELECT o.id                                    AS opportunity_id,
       COALESCE(o.eci__c,'')                   AS eci_id,
       COALESCE(o.ownersid__c,'')              AS ownersid,
       COALESCE(o.account_record_type_name__c,'') AS account_record_type,
       COALESCE(o.product_service_type__c,'')  AS product_service_type,
       COALESCE(o.stagename,'')                AS stage_name,
       COALESCE(o.amount,0)                    AS amount,
       COALESCE(o.actual_assets__c,0)          AS actual_assets,
       o.anticipated_investment_date__c        AS anticipated_investment_dt,
       o.createddate                           AS created_dt,
       o.lastmodifieddate                      AS last_modified_dt,
       o.date_of_last_contact__c               AS date_of_last_contact,
       COALESCE(o.days_to_close,0)             AS days_to_close,
       COALESCE(o.additional_comments__c,'')   AS comments
FROM   <crm_table> o
WHERE  regexp_replace(COALESCE(o.ownersid__c,''), '_.*$', '') IN ('T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017')
   OR  o.eci__c IN (
         SELECT DISTINCT r.party_eci_id
         FROM   pcr.fpic_acct_eci_rel_tb_pm r
         JOIN   pcr.fpic_revenue_transaction_tb_pm t
                ON ltrim(trim(t.account_no),'0') = ltrim(trim(r.account_number),'0')
         WHERE  t.advisor_sid IN ('T000001','T000002','T000003','T000005','T000004',
                         'T000018','T000019','T000020','T000006','T000007',
                         'T000008','T000009','T000010','T000011','T000012',
                         'T000013','T000014','T000015','T000016','T000017')
       );
